### ISSUE TITLE
NPE from AutoScroller

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#163]
Steps to reproduce:
Open AOI.
Click on Objects pane with RMB to invoke popup menu.
Click on pane again. The NPE is outputs in log:

java.lang.NullPointerException
	at artofillusion.ui.AutoScroller.mouseReleased(AutoScroller.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at buoy.internal.EventLinkRecord.dispatchEvent(EventLinkRecord.java:81)
	at buoy.event.EventSource.dispatchEvent(EventSource.java:140)
	at buoy.widget.Widget.dispatchEvent(Widget.java:326)
	at buoy.internal.EventLinkAdapter.dispatchEvent(EventLinkAdapter.java:212)
	at buoy.internal.EventLinkAdapter.mouseReleased(EventLinkAdapter.java:108)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343)

I see that mouseReleased method calls twice and on second call tries to interrrupt already released scrollThred.
Easy to fix but not very clear why this method calls twice...

**Comment by Sailsman63** [comment]
Can you clarify your instructions here? I have not been able to reproduce this exception...

**Comment by peteihis** [comment]
I have seen this a lot, but I did not pay attention to how it happened. 

1) Click Objects Pane with Right MouseButton **on the empty the area past the object list**.
2) Click again with any button.

This pops the alert up. As a new symptom the NullPointer some times froze the UI entirely but that could be related to me trying to capture the event on video.

**Comment by makiam** [comment]
null object is AutoScroller scrollThread  which already nulled

**Comment by peteihis** [comment]
> null object is AutoScroller scrollThread which already nulled

I get that it is the scroll thread that causes the exception, but I was wondering, why the AutoScroller is activated at all in a case, when there is nothig to scroll to? I mean the mouse is clicked on empty background. Is there a possibility to do the check, where the mouse click is detected?

**Comment by makiam** [comment]
AutoScroller starts new thread on each mouseDown event of it's container component and releases it on mouseUp event. 
The error occurs when control fires not paired mouseUp event

**Comment by Sailsman63** [comment]
Sorry, I'm still not seeing this, either in the terminal output or with the log plugin.

What versions of Java/OSes are you seeing it with?

**Comment by peteihis** [comment]
Two Windows 10 PCs, Java 8 on one of them and both Java 8 and 11 on one of them, AoI 3.0.3 and AoI 3.1.0 on the PC with both Javas. I've got the feeling that this has been there for a very long time.

And again: screen capture video + this --> UI freeze.

**Comment by makiam** [comment]
See this on Windows 10 with java 8 and java 13. Not see on virtual mac with java 13

**Comment by Sailsman63** [comment]
Got it. Apparently windows-specific... (Did not show on ArchLinux, but did on Windows)
