### ISSUE TITLE
Raytracer needs a 'warm-up round'

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#252]
Hi.

I've got a Groovy script that uses raytracing. For some reason the first time I run it, it always ends with a `NullPointerException` and that never happens again during a session. This is not the first time run into this either, but the other case was technically very similar. That time I simply wrote a "warm-up" sequence that shot rays into the scene until an exception and then started the actual raytracig for the job.

This time I tried to trace back what happens. 

The script is calling the simpler form of `traceRay()`, which calls the other one. The exception happens in `Raytracer` on line 618 and the null is the `intersection` variable that get it's value from `Ray.findIntersection()` on line 615.

The `findIntersection()` gets it's value from `RTObject.checkIntersection()`. When there is nothing to return, `RTObject`s do not return `null`, they return `SurfaceIntersection.NO_INTERSECTION`. In the cases I managed to find, the return value should be `NO_INTERSECTION`.

Then I patched the 618 so that `null`s are changed to `NO_INTERSECTION`s.

The next thing that went wrong was in the script: `java.lang.NullPointerException: Cannot invoke method getObject() on null object`. The `null` was produced by `RayIntersection.getFirst()`. Once I got those cases picked out the script did it's job at first attempt and I did not even see any missing pixels that I was expecting.

It looks like every `RTObject` on the scene would at some point send one `null instead of `NO_INTERSECTION`. Then quite a few of those may come before `getFirst()` returns `null`. After that happens, the problem seem to be over.

It does not matter if the script uses multithreading or not.

Any idea what's going on? Does the simpler `traceRay()` somehow affect? Is it because of Groovy? _(Groovy sometimes does pretty strange things. The latest quirk is that it is afraid on number 9 in the the script code...)_ And how come it gets fixed by using the Raytracer until the first exception case?

**Comment by Sailsman63** [comment]
What is the exact stacktrace for the original error?

**Comment by peteihis** [comment]
~~~~
java.lang.NullPointerException
	at artofillusion.raytracer.Raytracer.traceRay(Raytracer.java:618)
	at artofillusion.raytracer.Raytracer.traceRay(Raytracer.java:590)
	at artofillusion.raytracer.Raytracer$traceRay$2.call(Unknown Source)
	at Script1$2.execute(Script1.groovy:257)
	at artofillusion.util.ThreadManager$1.run(ThreadManager.java:94)
~~~~

That's all there is.

**Comment by peteihis** [comment]
One point: `TaskManager` 94 is `task.execute(index);`in a try block. In the following catch block like 98 is               `task.cleanup();` but the `.cleanup`in the script is just an empty block.

**Comment by Sailsman63** [comment]
Well, I don't know what is wrong here yet, but two interesting facts:

- The `traceRay(vec3, vec3)` has not been *used* by any core code since @peastman split the `RayTracer` proper from the `RayTracerRenderer` 
- There were a few changed made to it at that time.

Question: do you remember when you first noticed this? Was it before or after that thread-contention issue that you discovered and I patched a few years back?

**Comment by peteihis** [comment]
> Was it before or after that thread-contention issue that you discovered and I patched a few years back?

Just after. Based on dates of the posts on the forum & some pictures I found. ... Dunno where I put that script though....

**Comment by Sailsman63** [comment]
Okay. Do you also remember if the script that you were using at that time worked *before* we patched that thread issue?

**Comment by peteihis** [comment]
I wrote that script about a month after the fix.

And I found the script and tested with about a year older AoI. Same thing. Only the line numbers that are reported have shifted a few lines from that version. There have been some fixes and probably added comments on RT since then.

**Comment by Sailsman63** [comment]
Is your current script the DepthMapRenderer?

- If so, I don't see a warmup round in the code, and I don't get this exception.
- If not, how does the scene prep differ between the DMR and the script that causes this exception?

**Comment by peteihis** [comment]
No it is not the DMR and there is no warm-up in that one. The current caseis basically derived/further developed from the multithreading DMR. The other one was the Physical Properties Scanner. That one does not multithread.

With the multithreading thing it looks like the problem would be queying happen in every (or at least several) thread. The first one that gets through triggers the exception. That would explain the results of one of my strange debugging attempts.

I'll try to post some kind of minimal test set later, now the cases that I have are not very presentable.

**Comment by peteihis** [comment]
I did some checking. 

This happens with both of the DeptMapRenderers, [single thread ](https://sourceforge.net/p/aoi/discussion/228117/thread/2d50b3fb/#f697) and [multi thread](https://sourceforge.net/p/aoi/discussion/47784/thread/c8797e17/#dd0f) and with this attached one.

[Scanner 360_Test.zip](https://github.com/ArtOfIllusion/ArtOfIllusion/files/5825597/Scanner.360_Test.zip)

The ´Scanner 360` uses the war-up routine. All it has to do is to send one ray. The next one already hit's something. I don't know what would happen if the first ray didn't hit an object, but it probably has to. 

The OS is Windows 10 and it happens on every HW that I have tested. And to have it happen you need to start AoI, open or create a scene, start the script and run it once. When you run it the next time the problem is not there any more.

**Comment by Sailsman63** [comment]
Have you tested with different JVMs?

I have not been able to reproduce this at all. So far, it seems to be Windows specific...

@peastman @makiam does this show up on mac?

This could also be a bug in our (Ancient) groovy implementation, but since I can't duplicate the issue, I can't test if updating groovy makes a difference.

**Comment by peteihis** [comment]
> Have you tested with different JVMs?

Oracle Javas 8 and 11 and AO-Java 11. (All JDK I think...)

**Comment by Sailsman63** [comment]
Okay, finally duplicated. 

So: First ray *must* intersect an object to trigger this exception.

Back to the drawing board. Would you be willing to try with an updated groovy, just to make sure that it's not a groovy bug? 

Check https://groovy.apache.org/download.html#distro for their latest. You might need to un-zip and sort through to find the right jars.

**Comment by peteihis** [comment]
> So: First ray must intersect an object to trigger this exception.

Without any warm-up it appeared to me that the the first ray that hit an object triggered it. Scanning empty space in the beginning of the sequence did not suppress what ever is happening there. But on the next  attempt everything was always working. I remember that there has been some variation has it happens. Sometimes there has been a small piece of a successfully scanned object before the exception. Somehow the warm-up thing still manages to take care of it.

> Would you be willing to try with an updated groovy. 

I will. Tomorrowish....

**Comment by Sailsman63** [comment]
Huh... because I can't duplicate until I zoom in so far that the entire screen is filled with <object>. (Or the object is large enough that it fills the screen from a distance.)

This implies to me that (as far as I've seen it, anyway) once one or two rays are successfully traced, the rest should be fine.

**Comment by makiam** [comment]
See no troubles with given script neither on Windows nor on my virtual Mac

**Comment by peteihis** [comment]
> See no troubles with given script neither on Windows nor on my virtual Mac

By given script you mean the Scanner 360_Test.groovy? 

Try this: 
- Disable the call to `warmUp()` on line 641.
- Save the script.
- Shut down AoI entirely.
- Restart and load or create a scene.
- Run the modified script once. There should be an error message.
- Run again. Should now work normally.

**Comment by makiam** [comment]
![rtest](https://user-images.githubusercontent.com/16633367/104965877-b0502e80-59f0-11eb-9fd3-e0d05cf59f55.png)

**Comment by peteihis** [comment]
Duplicated.

This way done script works as if nothing was wrong.

If place the the object right above the camera it renders about 5 mm from the left and then stops. There is no error message but the image does not get finished either. Threads don't fill the table quite the order they are created. There rendered part may be in a couple of stripes. When I scan again the image is fully rendered.

**Comment by peteihis** [comment]
> with an updated groovy

groovy-4.0.0-alpha-2.jar

No change. Also `NaN == NaN` still returns `true` so I don't expect any of the strangeish math solutions would have been fixed.

**Comment by Sailsman63** [comment]
Sorry for the long silence here. Do you know if this issue occurs with similar scripts written in beanshell?

**Comment by peteihis** [comment]
> Do you know if this issue occurs with similar scripts written in beanshell?

No idea, never occurred to me to test so far. 

Anyway I got the job, where I needed raytracing, done (for all I know). To test in BS I'd probably just build a pair of a bit more simple scripts that just can indicate if the issue is there. Not right now though.

**Comment by Sailsman63** [comment]
Okay, I've confirmed that this *does* happen when triggered from beanshell, as well. I also have a thought on what might be happening courtesy of the timing issues that are addressed in #260, as well as the issues with the framing code that came up in the STLTranslator discussions. More digging...

**Comment by Sailsman63** [comment]
Also, this does transfer between the scripting environments, IE if it's triggered in groovy, the test script in beanshell will then behave as if it had already had a "Warmup" run.

**Comment by peteihis** [comment]
> Also, this does transfer between the scripting environments

That is weird.... 

It somehow begins to seems like there was something happening beyond the RayTracer code. At least I could not figure out, what in the code itself could have caused it. The threading system might be one suspect to have a look at. At least Groovy tends to have a mind of it's own some times (threads and recursion are where I have seen it stumble).

**Comment by Sailsman63** [comment]
But if I trigger it in beanshell, the *groovy* version behaves correctly. 

I had thought to blame groovy's threading/context stuff, but this makes me think that it *is* the raytracer code, or at least some bit of AOI code that both scripting environments depend on.
